name: Build
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install
      - run: node build.js
      # Commit the changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          message: "Build"
          branch: master
